name: Weekly Shopify Report

on:
  schedule:
    # Run every Monday at 12:00 AM Mountain Time
    - cron: '0 7 * * 1'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  generate_report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "SHOP_NAME=${{ secrets.SHOP_NAME }}" > .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "API_VERSION=${{ secrets.API_VERSION }}" >> .env
        echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
    
    - name: Create service account key file
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > supple-life-437019-e0-7d94cf81533f.json
    
    - name: Run Shopify report script
      run: python shopify_reports.py
    
    - name: Upload reports to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: shopify-reports
        path: reports/
        retention-days: 30