name: Weekly Shopify Report

on:
  schedule:
    # Run every Monday at 7 AM UTC (12 AM Mountain Time in winter, 1 AM in summer)
    - cron: "0 7 * * 1"

  # Allow manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "catch-up"
        type: choice
        options:
          - weekly
          - historical-incremental
          - historical-full
          - catch-up

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "SHOP_NAME=${{ secrets.SHOP_NAME }}" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "API_VERSION=${{ secrets.API_VERSION || '2025-04' }}" >> .env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env

      - name: Create service account key file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > supple-life-437019-e0-f2c2876fac24.json

      - name: Check for existing spreadsheet ID
        id: spreadsheet_check
        run: |
          if [ -f "spreadsheet_config.txt" ]; then
            echo "Found existing spreadsheet ID in config file"
            echo "spreadsheet_id=$(cat spreadsheet_config.txt)" >> $GITHUB_OUTPUT
          else
            echo "No existing spreadsheet ID found, will use environment variable"
            echo "spreadsheet_id=${{ secrets.SPREADSHEET_ID }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Enhanced Shopify Historical Report
        run: |
          # Use catch-up mode for scheduled runs to ensure missing weeks are filled
          if [ "${{ github.event_name }}" = "schedule" ]; then
            MODE="catch-up"
          else
            MODE="${{ github.event.inputs.mode || 'catch-up' }}"
          fi

          echo "Running in mode: $MODE"
          echo "Using spreadsheet ID: ${{ steps.spreadsheet_check.outputs.spreadsheet_id }}"

          # Set the spreadsheet ID as environment variable for the script
          export SPREADSHEET_ID="${{ steps.spreadsheet_check.outputs.spreadsheet_id }}"

          # Run with verbose logging
          python shopify_reports.py --mode $MODE --spreadsheet-id "${{ steps.spreadsheet_check.outputs.spreadsheet_id }}"

      - name: Verify Google Sheets Update
        run: |
          echo "Checking if Google Sheets was updated..."
          if [ -f "reports/historical_summary.json" ]; then
            echo "✅ Historical summary found:"
            cat reports/historical_summary.json
          else
            echo "❌ No historical summary found - Google Sheets update may have failed"
            exit 1
          fi

          if [ -f "spreadsheet_config.txt" ]; then
            echo "✅ Spreadsheet ID saved: $(cat spreadsheet_config.txt)"
          else
            echo "❌ Spreadsheet ID not saved - this may cause future issues"
          fi

      - name: Upload reports to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shopify-reports-${{ github.run_id }}
          path: |
            reports/
            spreadsheet_config.txt
          retention-days: 30
          if-no-files-found: warn

      - name: Report completion
        if: success()
        run: |
          echo "✅ Shopify historical reporting completed successfully!"
          if [ -f "reports/historical_summary.json" ]; then
            echo "📊 Summary:"
            cat reports/historical_summary.json
          fi

          # Check if we need to catch up on missing weeks
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.mode }}" = "historical-incremental" ]; then
            echo "⚠️  Note: You ran in incremental mode. If you're missing weeks since 06-01, run with 'catch-up' mode to fill the gaps."
          fi

      - name: Clean up credentials
        if: always()
        run: |
          rm -f supple-life-437019-e0-f2c2876fac24.json
          rm -f .env
